org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.252
loader_version_range=[1,)

mod_id=signalradar
mod_name=Signal Radar
mod_license=MIT
mod_version=1.0.0
mod_group_id=it.ratlab.signalradar

# Optional dependency version range (mods.toml)
kubejs_version_range=[2101.7,)
manholes_version_range=[1.5,)
lootr_version_range=[1.11,)
ftbteams_version_range=[2101.1,)
